name: flutter_starter_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.2.0
  another_flushbar: ^1.10.24
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  equatable: ^2.0.3
  file_picker: ^4.2.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.3
  flutter_page_indicator_tv: ^0.0.3-nullsafety
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  go_router: ^2.2.1
  image_picker: ^0.8.4+4
  injectable: ^1.5.0
  json_annotation: ^4.3.0
  linear_step_indicator: ^1.0.0+2
  path: ^1.8.0
  path_provider: ^2.0.6
  sembast: ^3.1.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  lint: ^1.7.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
